PROFILING_PROGRAM = True
DEBUGGING_NETWORK_MESSAGES = False
DEBUGGING_HITSCAN_WEAPON = False
# If CVD is true then SFD must be set
CLIENT_VISUAL_DEBUGGING = False # This gets set in client.py
SCREEN_FOR_DEBUGGING = None
EXPLOSIONS_FOR_DEBUGGING = []
