PROFILING_PROGRAM = True
DEBUGGING_NETWORK_MESSAGES = False
DEBUGGING_HITSCAN_WEAPON = False
DEBUGGING_INTERSECTIONS = False
# If CVD is true then SFD must be set
CLIENT_VISUAL_DEBUGGING = False # This gets set in client.py
SCREEN_FOR_DEBUGGING = None
EXPLOSIONS_FOR_DEBUGGING = []
INTERSECTED_PARTITION_PATCH_MARKERS = []
BEAMS_FOR_DEBUGGING = []
INTERSECTED_PARTITION_SEAMS_FOR_DEBUGGING = []
INTERSECTED_PARTITIONS_FOR_DEBUGGING = []
INTERSECTIONS_FOR_DEBUGGING = []
