import game_engine_constants

ROCKET_LAUNCHER_FIRE_RATE_HZ: int = 1

ROCKET_RADIUS: float = game_engine_constants.TILE_SIZE / 4

ROCKET_SPEED: int = 2000

ROCKET_EXPLOSION_RADIUS: int = 100

ROCKET_EXPLOSION_POWER: int = 750

ROCKET_EXPLOSION_SHARDS: int = 32

ROCKET_EXPLOSION_COLLISION_FORCE: int = 750

ROCKET_EXPLOSION_DAMAGE: int = 10

RAILGUN_FIRE_RATE_HZ: int = 1

RAILGUN_DAMAGE: int = 60

RAILGUN_COLLISION_FORCE: int = 60
